immob/urls.py
from django.conf.urls import url 
from django.urls import path
from .views import index, bien, contacter_agence, Login, Logout, register

app_name = 'immob'
urlpatterns = [
    path('', index, name='index'),
    url('biens', bien, name='biens'),
    url('contacter_agence', contacter_agence, name='contacter_agence'),
    url('Login', Login, name='Login'),
    url('Logout', Logout, name='Logout'),
    url('register', register, name='register'),
]

ndcimmob/urls.py
from django.contrib import admin
from django.urls import path, include
from immob.views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('immob/', include('immob.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

immob/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, PermissionsMixin, BaseUserManager
from django.conf import settings

class UserManager(BaseUserManager):

    use_in_migrations = True
    
    def _create_user(self, username, email, phone, password, **extra_fields):

        values = [username, email, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError("Le champ {} doit etre rempli".format(field_name))
        
        email = self.normalize_email(email)
        user = self.model(
            username=username,
            email=email,
            phone=phone,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_user(self, username, email, phone, password, **extra_fields):

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_active') is not True:
            raise ValueError("Une lié au droit d'accès c'est produite")

        return self._create_user(username, email, phone, password, **extra_fields)

    def create_superuser(self, username, email, phone, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', True),
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Le champ is staff ne pas être faux pour l'admin")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Le champ is superuser ne pas être faux pour l'admin")
        if extra_fields.get('is_active') is not True:
            raise ValueError("Le champ is active ne pas être faux pour l'admin")

        return self._create_user(username, email, phone, password, **extra_fields)
class User(AbstractUser, PermissionsMixin):

    username = models.CharField('Nom utilisateur', max_length=50, unique=True)
    first_name = models.CharField('Nom', max_length=50, null=True)
    first_name = models.CharField('Prénom', max_length=50, null=True)
    email =  models.EmailField(max_length=254, unique=True)
    phone = models.CharField('Contact', max_length=30, unique=True)
    news = models.BooleanField("Je souhaite m'abonner à la newslater")
    ag_admin = models.BooleanField("Administrateur agence", default=False)
    is_superuser = models.BooleanField(default=False)
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'phone']

    def __str__(self):

        return self.username

    def save(self, *args, **kwargs):

        self.passord = self.set_password(self.password)
        super(User, self).save(*args, **kwargs)



class Agence(models.Model):

    nom = models.CharField("Nom agence", max_length=128)
    status = models.BooleanField("Aggréer ou non", default=False)
    Commune = models.ForeignKey("Ville", verbose_name="Ville ou commune", on_delete=models.CASCADE)
    localite = models.CharField("Adresse postale", max_length=254)
    numero_agr = models.CharField("Numéro d'aggregation", max_length=50)
    regi_commerce = models.CharField("Regis de commerce", max_length=128)
    num_cpte = models.CharField("Numero de compte contribiable", max_length=50)
    dg = models.OneToOneField("User", verbose_name="Propriétaire", on_delete=models.CASCADE)


class Ville(models.Model):
    
    ville = models.CharField(max_length=128)

    def __str__(self):
        return self.ville

    
class Types(models.Model):

    libele = models.CharField(max_length=128)

    def __str__(self):
        return self.libele


class Offre(models.Model):
    
    titre = models.CharField(max_length=128)

    

    def __str__(self):
        return self.titre

class Demande(models.Model):
    
    libele = models.CharField(max_length=128)

    def __str__(self):
        return self.libele


class Immobilier(models.Model):
    
    type_immob = models.ForeignKey("Types", verbose_name="Type de bien", on_delete=models.CASCADE)
    nombre = models.IntegerField("Nombre de pièces")
    surface = models.IntegerField("Surface en m²")
    commune = models.ForeignKey("Ville", verbose_name="Ville ou commune", on_delete=models.CASCADE)
    prix = models.IntegerField("Prix de loyer souhaité")
    adresse = models.CharField("Adresse postale", max_length=254)
    image = models.ImageField(upload_to=settings.MEDIA_ROOT)
    image_1 = models.ImageField(upload_to=settings.MEDIA_ROOT)
    image_2 = models.ImageField(upload_to=settings.MEDIA_ROOT, blank=True, null=True)
    desc = models.TextField("Description du bien")
    status = models.ForeignKey("Offre", verbose_name="Faite un choix", on_delete=models.CASCADE)
    user = models.ForeignKey("User", verbose_name="Propriétaire", on_delete=models.CASCADE)


   
    def __str__(self):
        return self.type_immob


class Besoins(models.Model):

    type_bien = models.ForeignKey("Types", verbose_name="Type de bien", on_delete=models.CASCADE)
    nombre = models.IntegerField("Nombre de pièces")
    surface = models.IntegerField("Surface minimale en m²")
    prix = models.IntegerField("Prix minimum")
    prix_2 = models.IntegerField("Prix maximum")
    demande = models.ForeignKey("Demande", verbose_name="Type de besoin", on_delete=models.CASCADE)
    commune = models.ForeignKey("Ville", verbose_name="Ville ou commune", on_delete=models.CASCADE)
    adresse = models.CharField("Adresse postale", max_length=254)
    user = models.ForeignKey("User", verbose_name="Demandeur", on_delete=models.CASCADE)

    def __str__(self):
        return self.type_besoin

   

immob/forms.py
from django import forms
from .models import User, Besoins

class UserCreationForm(forms.ModelForm):

    password = forms.CharField(label="Mot de passe", max_length=254, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Mot de passe'}))
    password1 = forms.CharField(label="Confirmer le mot de passe", max_length=254, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmer votre mot de passe'}))

    
    class Meta:
        model = User
        fields = ("username", "email", 'phone', 'password', 'password1', 'news',)
        widgets = {
            'username': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Nom utilisateur'
					}
				),
            'email': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Votre mail'
					}
				),
            'phone': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Votre contact'
					}
				),
            'news': forms.CheckboxInput(
				attrs={
					'class': 'form-check-input'
					}
				),
            
			}

class BesoinForm(forms.ModelForm):
    
    class Meta:
        model = Besoins
        fields = ("__all__")
       

            

immob/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .forms import UserCreationForm, BesoinForm
import json


def index(request):

    if loggedUser(request):
        return render(request, 'immob/index.html', { 'user' : request.user, 'log': loggedUser(request), 'userForm': UserCreationForm})

    return render(request, 'immob/index.html', { 'userForm': UserCreationForm })


def register(request):
    
    if len(request.POST) > 0:

        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(json.dumps({'message': "Success"}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'message': "Incomplete"}), content_type="application/json")

    return HttpResponse(json.dumps({'message': "No data"}), content_type="application/json")



def bien(request):

    if loggedUser(request):
        return render(request, 'immob/public/bien.html', { 'user': request.user, 'log': loggedUser(request)})
    
    return render(request, 'immob/public/bien.html', {'userForm': UserCreationForm})

def contacter_agence(request):

    if loggedUser(request):
        return render(request, 'immob/public/contacter_agence.html', { 'user': request.user, 'log': loggedUser(request)})

    return render(request, 'immob/public/contacter_agence.html', {'userForm': UserCreationForm})


def poster(request):

    besoinForm = BesoinForm()

    if len(request.POST) > 0:

        besoinForm = BesoinForm(request.POST)
        if loggedUser(request)
            besoinForm.user = request.user

            if besoinForm.is_valid():
                besoinForm.save()
                




def Login(request):

    #Authentification
    email = request.POST['email']
    password = request.POST['password']

    user = authenticate(email=email, password=password) #Recupere l'utilisateur 

    if user is not None:
        if user.is_active:
            request.session['id'] = user.username #Ajout à la variable de session
            login(request, user) #Connexion
            return HttpResponse(json.dumps({'message': "Success"}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'message': "inactive"}), content_type="application/json")
    else:

        return HttpResponse(json.dumps({'message': "invalid"}), content_type="application/json") #Echec
    return HttpResponse(json.dumps({'message': "denied"}), content_type="application/json")
    

def Logout(request):

    #Deconnexion d'un utilisateur
    if loggedUser(request):
        del request.session['id']
        logout(request)
        return redirect('immob:index')
    else: #Si aucun utilisateur n'est connecté
        return None 

def loggedUser(request):

    #Voir si un utilisateur est connecté
    if 'id' in request.session:
        return True
    else:
        return False #Aucun utilisateur n'est connecté

immob/templates/immob/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <link rel="stylesheet" href="path/to/line-awesome/css/line-awesome-font-awesome.min.css">

    <link rel="stylesheet" href="{% static './immob/css/style.css'%}" />

    <title>Afrique Immobilier</title>
    <style>
        {% block styles %}

        {% endblock styles %}
    </style>
  </head>
  <body>
    <div class=''>
        <div class='row content'>

            <div class="col-sm cls-sm">
                
                {% if log == True %}
                  <a href="{% url 'immob:Logout' %}" type="button" class="btn btn-outline-secondary">Deconnexion</a>
                  <a href="#" type="button" class="btn btn-outline-secondary">{{user}}</a>
                {% else %}
                  <!--<a href="#" type="button" class="btn btn-outline-secondary">Inscription</a>-->
                  <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#signup" data-whatever="@mdo">Inscription</button>
                  <!--<a href="{% url 'immob:Login' %}" type="button" class="btn btn-outline-secondary">Connexion</a>-->
                  <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#login" data-whatever="@mdo">Connexion</button>
                {% endif%}
            </div>
            <div class="col-sm">
                <center>
                    <strong>AFRIQUE</strong><span style='color: orange;'> IMMOBILIER</span>
                    <p><strong style='color: #aaa;'>VOTRE BIEN ETRE, NOTRE SOUCI</strong></center></p>
                </center>
            </div>
            <div class="col-sm">
                <i class="fas fa-cloud"></i>
                <i class="fas fa-coffee"></i>
                
            </div>

        </div>
        <hr>
        <header>
            <nav>
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'immob:index' %}">ACCUEIL</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link text-dark" href="#">NOS SERVICES</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="dropdown-toggle drop" data-toggle="dropdown">
                              OPPORTUNITES
                            </a>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{% url 'immob:biens' %}">MES POSTES</a>
                              <a class="dropdown-item" href="#">POSTES DES AUTRES</a>
                            </div>
                          </div>
                        
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="dropdown-toggle drop" data-toggle="dropdown">
                              BESOINS
                            </a>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="#">MES BESOINS</a>
                              <a class="dropdown-item" href="#">BESOINS DES AUTRES</a>
                            </div>
                          </div>
                        
                    </li>
                    <li class="nav-item">
                    <a class="nav-link text-dark" href="#">CONTACTS</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link text-dark" href="#">RECHERCHER UN BIEN</a>
                    </li>
                    <li class="nav-item">
                      <a class=" btn btn-dark nav-link bg-warning text-white" style="border: none;" href="#">POSTER VOTRE BIEN</a>
                    </li>
                </ul>
            </nav>
        </header>
       
       {% block hr_br %}
        <br>
       {% endblock hr_br %}
       
    </div>

    
    <div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Connexion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="email" class="col-form-label">Email:</label>
                <input type="email" class="form-control" id="email">
              </div>
              <div class="form-group">
                <label for="password" class="col-form-label">Mot de passe:</label>
                <input type="password" class="form-control" id="password">
              </div>
              <div id="errorlogin" style="color:red"></div>
              <div class="modal-footer">
                <button type="button" id="sub" class="btn btn-outline-secondary" value="Se connecter">Se connecter</button>
              </div>
            </form>
          </div>
          
        </div>
      </div>
    </div>

    <div class="modal fade" id="signup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Inscription</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="id_username" class="col-form-label">{{userForm.username.label}}</label>
                {{ userForm.username }}
              </div>
              <div class="form-group">
                <label for="id_email" class="col-form-label">{{userForm.email.label}}</label>
                {{ userForm.email }}
              </div>
              <div class="form-group">
                <label for="id_phone" class="col-form-label">{{userForm.phone.label}}</label>
                {{ userForm.phone }}
              </div>
              <div class="form-group">
                <label for="id_password" class="col-form-label">{{userForm.password.label}}</label>
                {{ userForm.password }}
              </div>
              <div class="form-group">
                <label for="id_password1" class="col-form-label">{{userForm.password1.label}}</label>
                {{ userForm.password1 }}
              </div>
              <div class="form-check">
                <label for="id_news" class="form-check-label">{{userForm.news.label}}</label>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ userForm.news }}
              </div>
              
              <div id="errorlogins" style="color:red"></div>
              <div class="modal-footer">
                <button type="button" id="signup" class="btn btn-outline-secondary" value="">S'inscrire</button>
              </div>
            </form>
          </div>
          
        </div>
      </div>
    </div>

    {% block content %}
        {% block search %}
        
        {% endblock search %}
    {% endblock content %}


    <footer class="mt-5 bg-warning">
        <div class="row">
          <div class="col-sm"></div>
          <div class="col-sm">
            <center>
              <p><a href="#">Afrique Immobilier</a></p>
              <p><a href="#">immobafric@gmail.com</a></p>
            </center>
          </div>
          <div class="col-sm"></div>
        </div>
      </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    
    <script>

        var login = document.getElementById('login')
        login.addEventListener('show.bs.modal', function (event) {
          // Button that triggered the modal
          var button = event.relatedTarget
          // Extract info from data-bs-* attributes
          var recipient = button.getAttribute('data-bs-whatever')
          // If necessary, you could initiate an AJAX request here
          // and then do the updating in a callback.
          //
          // Update the modal's content.
          var modalTitle = login.querySelector('.modal-title')
          var modalBodyInput = login.querySelector('.modal-body input')

          modalTitle.textContent = 'New message to ' + recipient
          modalBodyInput.value = recipient
        });

        var signup = document.getElementById('signup')
        signup.addEventListener('show.bs.modal', function (event) {
          // Button that triggered the modal
          var button = event.relatedTarget
          // Extract info from data-bs-* attributes
          var recipient = button.getAttribute('data-bs-whatever')
          // If necessary, you could initiate an AJAX request here
          // and then do the updating in a callback.
          //
          // Update the modal's content.
          var modalTitle = signup.querySelector('.modal-title')
          var modalBodyInput = signup.querySelector('.modal-body input')

          modalTitle.textContent = 'New message to ' + recipient
          modalBodyInput.value = recipient
        });

        $(document).ready(function(){
          $("#sub").click(function(){
            email = document.getElementById("email").value;
            password = document.getElementById("password").value;
            csrfmiddlewaretoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
            $("#errorlogin").html("");
            $.ajax({
              type: 'POST',
              url: "{% url 'immob:Login' %}/",
              data: {
                'csrfmiddlewaretoken': csrfmiddlewaretoken,
                'email': email,
                'password': password,
              },
              success: function(data){
                console.log(data);
                if (data['message'] == "Success"){
                  location.reload();
                }else if (data['message'] == 'inactive'){
                  $("#errorlogin").html("S'il vous plait veillez verifier votre mail !");
                }else{
                  $("#errorlogin").html("Votre mot de passe ou email est incorrecte !");
                }
              }
            });
            })

            /*Registration*/
          $("#signup").click(function(){
            username = document.getElementById("id_username").value;
            email = document.getElementById("id_email").value;
            phone = document.getElementById("id_phone").value;
            password = document.getElementById("id_password").value;
            password1 = document.getElementById("id_password1").value;
            news = document.getElementById("id_news").value;
            csrfmiddlewaretoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
            $("#errorlogins").html("");
            $.ajax({
              type: 'POST',
              url: "{% url 'immob:register' %}/",
              data: {
                'csrfmiddlewaretoken': csrfmiddlewaretoken,
                'username': username,
                'email': email,
                'phone': phone,
                'password': password,
                'password1':password1,
                'news':news,
              },
              success: function(data){
                console.log(data);
                if (data['message'] == "Success"){
                  location.reload();
                }else if (data['message'] == 'Incomplete'){
                  $("#errorlogins").html("Vous n'avez pas bien renseigné le formulaire !");
                }else{
                  $("#errorlogins").html("Vous n'avez pas soumi de data !");
                }
              }
            });
            })
        });

        {% block script %}

        {% endblock script %}
    </script>
</body>
</html>